<?php

namespace app\admin\common;

use think\Controller;
use think\Session;
use think\Request;
use app\admin\model\System;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('USER_ID', Session::get('user_id'));
        $request = Request::instance();
        $config = $this->getSystem();
        $this->getStatus($request, $config);
    }

    public function isLogin()
    {
        if (is_null(USER_ID)) {
            $this->error('用户未登录，无权访问后台', 'Login/login');
        }
    }

    public function alreadyLogin()
    {
        if (!is_null(USER_ID)) {
            $this->error('用户已经登录，请勿重复登录', 'Index/index');
        }
    }

    public function getSystem()
    {
        return System::get(1);
    }

    public function getStatus($request, $config)
    {
        if ($request->module != 'admin') {
            if ($config->status == 0) {
                $this->error('网站已关闭');
                exit();
            }
        }
    }
}